GET http://localhost:2500/
###

GET http://localhost:3000/?id=11
###

GET http://localhost:3000/?id=112

###

GET http://localhost:3000/?id=Another+folder

###


GET http://localhost:3000/?id=Another+folder/Try+this+folder

###

GET http://localhost:3000/?id=Another+folder/Try+this+folder234
